### PR TITLE
Dockerfile/K8s implementation, prod/dev run

### PR DESCRIPTION
**Pull request by jorgejesus**
⚠️ Before submitting the PR, make sure:

- `yarn test --passWithNoTests`
---

- Updated mailto for new inbox (info@soilsrevealed.org)
- Dockerfile prepared for K8s
-  New `run.sh` to kickstart a build process and then yarn start
- `run.sh` implements `production/develop` 

Description of the PR

## Testing instructions

Run docker container
`docker build -t soils-revealed` 
`docker run -p3001:3001 --env-file .env soils-revealed:latest /soils-revealed/run.sh production`
set `.env` variables

What to test? How to do it?

## Pivotal Tracker

Link to the task(s), if any

### CODE REVIEW

**Review by clementprdhomme — COMMENTED** [review]
Hi @jorgejesus,

I left some comment on the PR.

I also wanted to check with you what's the plan with the AWS server. As you can see in `.github/workflows/`, this repository is still configured to automatically deploy to AWS when commits are pushed to `develop` and `master`. This would deploy the staging and production environments. Are those not needed anymore? Is TNC aware of it?

**Comment by clementprdhomme** [comment]
Bouncing back on one of my previous comments, if we're to work on a new phase of this project, we'd like to keep having a staging environment on your new infrastructure and auto deployment with GitHub Actions, if possible.

We don't need it at this point, but I'd like to make sure this will be possible in the future. Thanks!

**Comment by jorgejesus** [comment]
Hi @clementprdhomme 

Thank you for your comments. I have made a new commit implementing `PORT` instead of `NODE_PORT`
Concerning the automatic deployment. On my fork I've implemented github app that when you have a push to the repository it automatically  builds a docker image and pushes to a dedicate repository from where k8s can pull it. I still have an issue on making k8s  recreating the pods when there is a new image/

When you merge into the vizzuality project. We need to have a fast zoom with you, so set up the repository  to send the trigger to google cloud build.

**Comment by clementprdhomme** [comment]
Thank you Jorge!

**Pull request merged**
